<?php

/**
 * Created by PhpStorm.
 * User: Seyni FAYE
 * Date: 15/02/2017
 * Time: 20:02
 */

namespace app\core\controllers;

use app\core\ApiClientSoap;

class ClientSoapController extends ApiClientSoap
{
    private static $instance = null;

    public static function initClientSoap() : ClientSoapController {
        if(static::$instance === null) self::$instance = new ClientSoapController();
        return self::$instance;
    }

    public function call($uri, $service, $params = [])
    {
        return parent::call($uri, $service, $params); // TODO: Change the autogenerated stub
    }

    public function callXML($uri, $xml, $soapAction)
    {
        return parent::callXML($uri, $xml, $soapAction); // TODO: Change the autogenerated stub
    }
}